# Generated by Django 3.2.2 on 2021-05-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='author',
            field=models.CharField(default='Your name', max_length=254),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
