# Generated by Django 3.2 on 2021-04-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20210421_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('toy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toys.toy')),
            ],
        ),
    ]
