# Generated by Django 3.2 on 2021-04-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='toy',
            new_name='toy_id',
        ),
        migrations.AddField(
            model_name='toy',
            name='campaign_id',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toys.campaign'),
        ),
    ]
