# Generated by Django 3.2.2 on 2021-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_toy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='campaign',
            field=models.BooleanField(default=False),
        ),
    ]
