# Generated by Django 3.2 on 2021-05-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20210421_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
