# Generated by Django 3.2 on 2021-05-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_toy_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='toy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toys.toy', verbose_name='Campaign Price'),
        ),
    ]
