# Generated by Django 3.2.2 on 2021-05-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_toy_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
