# Generated by Django 3.2 on 2021-05-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_alter_campaign_toy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='toy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toys.toy'),
        ),
    ]
