# Generated by Django 3.2.2 on 2021-05-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_delete_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='campaign',
        ),
    ]
