# Generated by Django 3.2 on 2021-05-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_alter_campaign_toy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='campaign_id',
            new_name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='toy_id',
        ),
    ]
