# Generated by Django 3.2.2 on 2021-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_remove_toy_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='campaign',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
