# Generated by Django 3.2.2 on 2021-05-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0008_toy_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='campaign',
            field=models.BooleanField(default=1),
        ),
    ]
